export type ActivityMap =
  {
    [key: string | number]: string | number
  }

export const integerActivitiesMap: ActivityMap  = {
  0: 'In vehicle',
  1: 'Biking',
  3: 'Still (not moving)',
  4: 'Unknown (unable to detect activity)',
  5: 'Tilting (sudden device gravity change)',
  7: 'Walking',
  8: 'Running',
  9: 'Aerobics',
  10: 'Badminton',
  11: 'Baseball',
  12: 'Basketball',
  13: 'Biathlon',
  14: 'Handbiking',
  15: 'Mountain biking',
  16: 'Road biking',
  17: 'Spinning',
  18: 'Stationary biking',
  19: 'Utility biking',
  20: 'Boxing',
  21: 'Calisthenics',
  22: 'Circuit training',
  23: 'Cricket',
  24: 'Dancing',
  25: 'Elliptical',
  26: 'Fencing',
  27: 'Football (American)',
  28: 'Football (Australian)',
  29: 'Football (Soccer)',
  30: 'Frisbee',
  31: 'Gardening',
  32: 'Golf',
  33: 'Gymnastics',
  34: 'Handball',
  35: 'Hiking',
  36: 'Hockey',
  37: 'Horseback riding',
  38: 'Housework',
  39: 'Jumping rope',
  40: 'Kayaking',
  41: 'Kettlebell training',
  42: 'Kickboxing',
  43: 'Kitesurfing',
  44: 'Martial arts',
  45: 'Meditation',
  46: 'Mixed martial arts',
  47: 'P90X exercises',
  48: 'Paragliding',
  49: 'Pilates',
  50: 'Polo',
  51: 'Racquetball',
  52: 'Rock climbing',
  53: 'Rowing',
  54: 'Rowing machine',
  55: 'Rugby',
  56: 'Jogging',
  57: 'Running on sand',
  58: 'Running (treadmill)',
  59: 'Sailing',
  60: 'Scuba diving',
  61: 'Skateboarding',
  62: 'Skating',
  63: 'Cross skating',
  64: 'Inline skating (rollerblading)',
  65: 'Skiing',
  66: 'Back-country skiing',
  67: 'Cross-country skiing',
  68: 'Downhill skiing',
  69: 'Kite skiing',
  70: 'Roller skiing',
  71: 'Sledding',
  73: 'Snowboarding',
  74: 'Snowmobile',
  75: 'Snowshoeing',
  76: 'Squash',
  77: 'Stair climbing',
  78: 'Stair-climbing machine',
  79: 'Stand-up paddleboarding',
  80: 'Strength training',
  81: 'Surfing',
  82: 'Swimming',
  83: 'Swimming (swimming pool)',
  84: 'Swimming (open water)',
  85: 'Table tennis (ping pong)',
  86: 'Team sports',
  87: 'Tennis',
  88: 'Treadmill (walking or running)',
  89: 'Volleyball',
  90: 'Volleyball (beach)',
  91: 'Volleyball (indoor)',
  92: 'Wakeboarding',
  93: 'Walking (fitness)',
  94: 'Nording walking',
  95: 'Walking (treadmill)',
  96: 'Waterpolo',
  97: 'Weightlifting',
  98: 'Wheelchair',
  99: 'Windsurfing',
  100: 'Yoga',
  101: 'Zumba',
  102: 'Diving',
  103: 'Ergometer',
  104: 'Ice skating',
  105: 'Indoor skating',
  106: 'Curling',
  108: 'Other activity',
  113: 'Crossfit',
  114: 'HIIT',
  115: 'Interval Training',
  116: 'Walking (stroller)',
  117: 'Elevator',
  118: 'Escalator',
  119: 'Archery',
  120: 'Softball',
  122: 'Guided Breathing',
  'Aerobics': 9,
  'Archery': 119,
  'Back-country skiing': 66,
  'Badminton': 10,
  'Baseball': 11,
  'Basketball': 12,
  'Biathlon': 13,
  'Biking': 1,
  'Boxing': 20,
  'Calisthenics': 21,
  'Circuit training': 22,
  'Cricket': 23,
  'Cross skating': 63,
  'Cross-country skiing': 67,
  'Crossfit': 113,
  'Curling': 106,
  'Dancing': 24,
  'Diving': 102,
  'Downhill skiing': 68,
  'Elevator': 117,
  'Elliptical': 25,
  'Ergometer': 103,
  'Escalator': 118,
  'Fencing': 26,
  'Football (American)': 27,
  'Football (Australian)': 28,
  'Football (Soccer)': 29,
  'Frisbee': 30,
  'Gardening': 31,
  'Golf': 32,
  'Guided Breathing': 122,
  'Gymnastics': 33,
  'HIIT': 114,
  'Handball': 34,
  'Handbiking': 14,
  'Hiking': 35,
  'Hockey': 36,
  'Horseback riding': 37,
  'Housework': 38,
  'Ice skating': 104,
  'In vehicle': 0,
  'Indoor skating': 105,
  'Inline skating (rollerblading)': 64,
  'Interval Training': 115,
  'Jogging': 56,
  'Jumping rope': 39,
  'Kayaking': 40,
  'Kettlebell training': 41,
  'Kickboxing': 42,
  'Kite skiing': 69,
  'Kitesurfing': 43,
  'Martial arts': 44,
  'Meditation': 45,
  'Mixed martial arts': 46,
  'Mountain biking': 15,
  'Nording walking': 94,
  'Other activity': 108,
  'P90X exercises': 47,
  'Paragliding': 48,
  'Pilates': 49,
  'Polo': 50,
  'Racquetball': 51,
  'Road biking': 16,
  'Rock climbing': 52,
  'Roller skiing': 70,
  'Rowing': 53,
  'Rowing machine': 54,
  'Rugby': 55,
  'Running': 8,
  'Running (treadmill)': 58,
  'Running on sand': 57,
  'Sailing': 59,
  'Scuba diving': 60,
  'Skateboarding': 61,
  'Skating': 62,
  'Skiing': 65,
  'Sledding': 71,
  'Snowboarding': 73,
  'Snowmobile': 74,
  'Snowshoeing': 75,
  'Softball': 120,
  'Spinning': 17,
  'Squash': 76,
  'Stair climbing': 77,
  'Stair-climbing machine': 78,
  'Stand-up paddleboarding': 79,
  'Stationary biking': 18,
  'Still (not moving)': 3,
  'Strength training': 80,
  'Surfing': 81,
  'Swimming': 82,
  'Swimming (open water)': 84,
  'Swimming (swimming pool)': 83,
  'Table tennis (ping pong)': 85,
  'Team sports': 86,
  'Tennis': 87,
  'Tilting (sudden device gravity change)': 5,
  'Treadmill (walking or running)': 88,
  'Unknown (unable to detect activity)': 4,
  'Utility biking': 19,
  'Volleyball': 89,
  'Volleyball (beach)': 90,
  'Volleyball (indoor)': 91,
  'Wakeboarding': 92,
  'Walking': 7,
  'Walking (fitness)': 93,
  'Walking (stroller)': 116,
  'Walking (treadmill)': 95,
  'Waterpolo': 96,
  'Weightlifting': 97,
  'Wheelchair': 98,
  'Windsurfing': 99,
  'Yoga': 100,
  'Zumba': 101
};
